Mobillogix/ClioBundle/Form/Model/ClioEventFilter.php
<?php

namespace Mobillogix\ClioBundle\Form\Model;

class ClioEventFilter
{
    /** @var string */
    private $id;

    /** @var string */
    private $tag;

    /** @var string */
    private $type;

    /** @var string */
    private $action;

    /**
     * @return bool
     */
    public function hasTag()
    {
        return !empty($this->tag);
    }

    /**
     * @return bool
     */
    public function hasType()
    {
        return !empty($this->type);
    }

    /**
     * @return bool
     */
    public function hasAction()
    {
        return !empty($this->action);
    }

    public function hasId()
    {
        return !empty($this->id);
    }

    /**
     * @return array
     */
    public function getTags()
    {
        return $this->explode($this->tag);
    }

    /**
     * @return array
     */
    public function getActions()
    {
        return $this->explode($this->action);
    }

    /**
     * @return array
     */
    public function getTypes()
    {
        return $this->explode($this->type);
    }

    private function explode($string)
    {
        if (empty($string)) {
            return [];
        }
        return array_map('trim', explode(',', $string));

    }

    /**
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param string $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return string
     */
    public function getTag()
    {
        return $this->tag;
    }

    /**
     * @param string $tag
     */
    public function setTag($tag)
    {
        $this->tag = $tag;
    }

    /**
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @param string $type
     */
    public function setType($type)
    {
        $this->type = $type;
    }

    /**
     * @return string
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * @param string $action
     */
    public function setAction($action)
    {
        $this->action = $action;
    }
}

Mobillogix/ClioBundle/Form/Type/ClioEventFilterType.php
<?php

namespace Mobillogix\ClioBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class ClioEventFilterType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('id', HiddenType::class, ['required' => false])
            ->add('tag', TextType::class, [
                'required' => false,
                'attr' => ['class' => 'form-control', 'placeholder' => 'Exact tag value, comma separated']
            ])
            ->add('action', TextType::class, [
                'required' => false,
                'attr' => ['class' => 'form-control', 'placeholder' => 'Exact action value, comma separated']
            ])
            ->add('type', TextType::class, [
                'required' => false,
                'attr' => ['class' => 'form-control', 'placeholder' => 'Exact type value, comma separated']
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Mobillogix\ClioBundle\Form\Model\ClioEventFilter',
            'method' => 'GET',
        ));
    }

    public function getName()
    {
        return '';
    }
}

Mobillogix/ClioBundle/Controller/ClioController.php
<?php

namespace Mobillogix\ClioBundle\Controller;

use Mobillogix\ClioBundle\Form\Model\ClioEventFilter;
use Mobillogix\ClioBundle\Form\Type\ClioEventFilterType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Pagerfanta\View\TwitterBootstrap3View;

/**
 * @Route("/clio")
 */
class ClioController extends Controller
{
    /**
     * @return \Symfony\Component\HttpFoundation\Response
     * @Route("/create", name="mobillogix_clio_create")
     * @Method(methods={"POST","GET","PUT"})
     */
    public function createTestAction()
    {
        $service = $this->get('mobillogix_clio.clio_service');

        $service->addEvent("web", "test", ["test"]);

        return new Response("Created");
    }

    /**
     * @param Request $request
     * @return Response
     * @Route("/{tag}")
     * @Route("/", name="mobillogix_clio_index")
     */
    public function indexAction(Request $request)
    {
        $filter = new ClioEventFilter();
        $form = $this->createForm(ClioEventFilterType::class, $filter);
        $form->handleRequest($request);
        $service = $this->get('mobillogix_clio.clio_service');

        $pager = $service->getRecordsByTagsPager($filter);
        $pager->setCurrentPage(max(1, (integer)$request->query->get('page', 1)));
        $pager->setMaxPerPage(max(5, min(50, (integer)$request->query->get('per_page', 20))));
        $pagerView = new TwitterBootstrap3View();
        $router = $this->container->get('router');
        $routeGenerator = function ($page) use ($router, $pager) {
            return $router->generate('mobillogix_clio_index',
                array('page' => $page, 'per_page' => $pager->getMaxPerPage()));
        };

        $events = $service->decorateEvents($pager->getCurrentPageResults());

        $layout = $this->container->getParameter('mobillogix_clio.layout');
        $template = $this->container->getParameter('mobillogix_clio.template');

        return $this->render($template, [
            'layout' => $layout,
            'filterForm' => $form->createView(),
            'filter' => $filter,
            'events' => $events,
            'eventsPager' => $pager,
            'eventsPagerView' => $pagerView,
            'eventsPagerGenerator' => $routeGenerator,
        ]);
    }
}

Mobillogix/ClioBundle/Resources/views/Clio/base.html.twig
{% block page_content %}{% endblock page_content %}

{% block page_javascript %}{% endblock page_javascript %}

{% block page_styles %}{% endblock page_styles %}

Mobillogix/ClioBundle/Resources/views/Clio/base_layout.html.twig
{% extends layout %}

{% block page_content %}{% endblock page_content %}

Mobillogix/ClioBundle/Resources/views/Clio/clio_utils.html.twig
{% macro render_json(value, as_text) %}
    <pre class="clio-json-content">{% if as_text %}{{ value }}{% else %}{{ value|json_encode }}{% endif %}</pre>
{% endmacro %}

{% macro render_yml(value, as_text) %}
    <pre class="clio-yml-content">{% if as_text %}{{ value }}{% else %}{{ value|yaml_dump(2) }}{% endif %}</pre>
{% endmacro %}

{% macro render_xml(value, as_text) %}
    <pre class="clio-xml-content">{% if as_text %}{{ value }}{% else %}{#TODO: implement#}{% endif %}</pre>
{% endmacro %}

Mobillogix/ClioBundle/Resources/views/Clio/index.html.twig
{% extends layout is not empty ? 'MobillogixClioBundle:Clio:base_layout.html.twig' : 'MobillogixClioBundle:Clio:base.html.twig' %}
{% import '@MobillogixClio/Clio/clio_utils.html.twig' as clio_utils %}
{% use '@MobillogixClio/Clio/clio_formats.html.twig' %}

{% block page_content %}
    <form action="{{ path('mobillogix_clio_index') }}" class="form-horizontal" style="border: 1px #DEDEDE solid; padding: 10px; border-radius: 5px; margin-bottom: 15px; background-color: #FEFEFE; ">
        <div class="form-group">
            <div class="col-sm-3">
                <a href="#" data-target="{{ filterForm.tag.vars.id }}" class="cross"><i class="glyphicon glyphicon-remove-circle"></i></a>
                {{ form_widget(filterForm.tag) }}
            </div>
            <div class="col-sm-3">
                <a href="#" data-target="{{ filterForm.action.vars.id }}" class="cross"><i class="glyphicon glyphicon-remove-circle"></i></a>
                {{ form_widget(filterForm.action) }}
            </div>
            <div class="col-sm-3">
                <a href="#" data-target="{{ filterForm.type.vars.id }}" class="cross"><i class="glyphicon glyphicon-remove-circle"></i></a>
                {{ form_widget(filterForm.type) }}
            </div>
            <div class="col-sm-2">
                <input type="submit" class="form-control" value="Filter">
            </div>
        </div>
    </form>

    Current server time: <strong>{{ "now"|date }}</strong>
    {{ block('clio_pager') }}
    {% block clio_template %}
        <table class="table table-bordered clio-events">
            <thead>
            <tr>
                <th>Information</th>
                <th>Data</th>
            </tr>
            </thead>
            <tbody>
            {% for event in events %}
                {{ block('clio_content') }}
            {% endfor %}
            </tbody>
        </table>
    {% endblock clio_template %}
    {{ block('clio_pager') }}
{% endblock page_content %}

{% block clio_pager %}
    {% if eventsPager.haveToPaginate %}
        <div class="pull-right pagerfanta">
            {{ pagerfanta(eventsPager) }}
        </div>
{#
        <div class="pull-right">
        {{ eventsPagerView.render(eventsPager, eventsPagerGenerator)|raw }}
        </div>
#}
    {% endif %}
{% endblock clio_pager %}

{% block clio_content %}
    {% set name = event.type ~ '_' ~ event.action %}

    {% set _block = block('clio_' ~ name) %}
    {% if _block is not empty %}
        {{ _block|raw }}
    {% else %}
        {{ block('clio_default') }}
    {% endif %}
{% endblock %}

{% block clio_default %}
    <tr>
        <td>
            {% block clioevent_info %}
                <a href="{{ url('mobillogix_clio_index', {'id': event.persistedId}) }}">#</a> <strong>{{ event.type }}:{{ event.action }}</strong>
                <p class="small">{{ event.createdAt ? event.createdAt|date : 'Unknown' }}</p>
                Tags:
                <ul>
                {% for tag in event.tags %}
                    <li>
                        <a href="{{ path('mobillogix_clio_index', {tag: tag}) }}">{{ tag }}</a>
                    </li>
                {% else %}
                    <li>No tags</li>
                {% endfor %}
                </ul>
            {% endblock clioevent_info %}
        </td>
        <td class="clio-data-container">
            {% set _block = block('clio_' ~ event.type ~ '_' ~ event.action ~ '_meta') %}{% if _block is not empty %}{{ _block|raw }}{% else %}{{ block('clioevent_meta') }}{% endif %}
            {% set _block = block('clio_' ~ event.type ~ '_' ~ event.action ~ '_params') %}{% if _block is not empty %}{{ _block|raw }}{% else %}{{ block('clioevent_params') }}{% endif %}
        </td>
    </tr>
{% endblock clio_default %}

{% block clioevent_params %}
    {% if event.params is not empty %}
        <pre>{{ event.params|yaml_encode(2) }}</pre>
    {% else %}
        No data to display
    {% endif %}
{% endblock clioevent_params %}

{% block clioevent_meta %}
    <div class="alert alert-info small" style="padding: 5px 15px; margin-bottom: 5px;">
        {% set meta = event.meta %}
        {% set meta_id = 'clio-meta-details-' ~ event.persistedId %}
        {% if 'command' == meta.issuer_type %}
            Command {% if meta.issuer_cli is defined %}<strong>{{ meta.issuer_cli|join(' ') }}</strong>{% endif %}
        {% endif %}
        {% if 'api' == meta.issuer_type %}
            Web request {% if meta.issuer_url is defined %}<strong>[{{ meta.issuer_method }}
            ] {{ meta.issuer_url }}</strong>{% if meta.issuer_instance is defined %} from '
                <strong>{{ meta.issuer_instance }}</strong>'{% endif %}{% endif %}
        {% endif %}
        <a href="#" onclick="$('#{{ meta_id }}').toggle(); return false;"><i
                    class="glyphicon glyphicon-circle-arrow-down" title="Click to toggle details"></i></a>
        <pre id="{{ meta_id }}" style="display: none;">{{ event.meta|yaml_encode(2) }}</pre>
    </div>
{% endblock clioevent_meta %}

{% block page_javascript %}
{{ parent() }}
<script>
    var tags = {{ filter.tags|json_encode|raw }};

    $('.clio-data-container').each(function(index, element) {
        var innerHTML = element.innerHTML;
        for (var i = 0; i < tags.length; i++) {
            var tag = tags[i];
            element.innerHTML = innerHTML.replace(new RegExp(tag, "g"),'<span class="highlight">' + tag + '</span>');
        }
    });

    $('a.cross').on('click', function(event){
        event.preventDefault();
        var id = $(this).attr('data-target');
        $('#'+id).val('');
    });

</script>
{% endblock page_javascript %}

{% block page_styles %}
<style>
    .highlight {
        background-color: rgba(255, 153, 0, 0.36);
        padding: 5px;
        margin: -5px;
        border-radius: 5px;
    }
    a.cross {
        position: absolute;
        right: 24px;
        top: 8px;
    }
</style>
{% endblock page_styles %}